from dataclasses import dataclass, asdict
from typing import Dict, List, Any


@dataclass
class ExperimentConfig:
    bandwidth_mbps: float = 8.0
    net_delay_ms: float = 0.0
    ai_resolution: int = 360
    ai_fps: float = 8.0
    window_seconds: float = 4.0
    stride_seconds: float = 4.0
    extra_ai_delay_ms: float = 0.0
    jpeg_quality: int = 75
    h264_batch_size: int = 1
    max_duration_sec: float = 20.0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# 单次实验默认参数
DEFAULT_CONFIG = ExperimentConfig(
    bandwidth_mbps=8.0,
    net_delay_ms=0.0,
    ai_resolution=360,
    ai_fps=8.0,
    window_seconds=4.0,
    stride_seconds=4.0,
    extra_ai_delay_ms=0.0,
    jpeg_quality=75,
    h264_batch_size=1,
    max_duration_sec=20.0,
)


DEFAULT_BATCH_GRID = {
    "bandwidth_mbps": [0.5, 1.0, 2.0, 4.0, 8.0, 16.0],
    "net_delay_ms": [0.0, 50.0, 100.0, 200.0],
    "ai_resolution": [224, 320, 360, 480],
    "ai_fps": [4.0, 6.0, 8.0, 12.0],
    "window_seconds": [1.0, 2.0, 4.0, 6.0],
    "extra_ai_delay_ms": [0.0, 50.0, 100.0],
    "jpeg_quality": [55, 75],
    "h264_batch_size": [1, 2, 4],
}


# 更推荐你正式汇报直接用“显式实验清单”，不要用笛卡尔积
# 这样每组实验意义清晰，也不会组合爆炸
EXPERIMENT_LIST: List[Dict[str, Any]] = [
    # =========================================================
    # 0. 基线
    # =========================================================
    {
        "name": "base",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },

    # =========================================================
    # 1. 带宽敏感性（更细）
    # =========================================================
    {
        "name": "bw_0_5",
        "bandwidth_mbps": 0.5,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw_1",
        "bandwidth_mbps": 1.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw_2",
        "bandwidth_mbps": 2.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw_4",
        "bandwidth_mbps": 4.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw_8",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw_16",
        "bandwidth_mbps": 16.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },

    # =========================================================
    # 2. 网络延迟敏感性
    # =========================================================
    {
        "name": "delay_50",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 50.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "delay_100",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 100.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "delay_200",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 200.0,
        "ai_resolution": 360,
        "ai_fps":24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },

    # =========================================================
    # 3. 分辨率敏感性
    # =========================================================
    {
        "name": "res_224",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 224,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "res_320",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 320,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "res_480",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 480,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },

    # =========================================================
    # 4. FPS 敏感性
    # =========================================================
    {
        "name": "fps_4",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 4.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "fps_6",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 6.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "fps_12",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 12.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },

    {
        "name": "fps_24",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },

    

    # =========================================================
    # 5. 窗口敏感性（加入 1s）
    # =========================================================
    {
        "name": "win_1",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "win_2",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 2.0,
        "stride_seconds": 2.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "win_3",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 3.0,
        "stride_seconds": 3.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "win_6",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 6.0,
        "stride_seconds": 6.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },

    # =========================================================
    # 6. H264 batch size 敏感性
    # =========================================================
    {
        "name": "batch_2",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 2,
        "max_duration_sec": 20.0,
    },
    {
        "name": "batch_4",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 4,
        "max_duration_sec": 20.0,
    },

    # =========================================================
    # 7. 带宽 × 窗口 交叉实验（重点增强）
    # =========================================================
    {
        "name": "bw0_5_win1",
        "bandwidth_mbps": 0.5,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw0_5_win2",
        "bandwidth_mbps": 0.5,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 2.0,
        "stride_seconds": 2.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw0_5_win4",
        "bandwidth_mbps": 0.5,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 4.0,
        "stride_seconds": 4.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw0_5_win6",
        "bandwidth_mbps": 0.5,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 6.0,
        "stride_seconds": 6.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },

    {
        "name": "bw2_win1",
        "bandwidth_mbps": 2.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw2_win2",
        "bandwidth_mbps": 2.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 2.0,
        "stride_seconds": 2.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw2_win4",
        "bandwidth_mbps": 2.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 4.0,
        "stride_seconds": 4.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw2_win6",
        "bandwidth_mbps": 2.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 6.0,
        "stride_seconds": 6.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },

    {
        "name": "bw8_win1",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw8_win2",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 2.0,
        "stride_seconds": 2.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw8_win6",
        "bandwidth_mbps": 8.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 6.0,
        "stride_seconds": 6.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },

    {
        "name": "bw16_win1",
        "bandwidth_mbps": 16.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 1.0,
        "stride_seconds": 1.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw16_win2",
        "bandwidth_mbps": 16.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 2.0,
        "stride_seconds": 2.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw16_win4",
        "bandwidth_mbps": 16.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 4.0,
        "stride_seconds": 4.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
    {
        "name": "bw16_win6",
        "bandwidth_mbps": 16.0,
        "net_delay_ms": 0.0,
        "ai_resolution": 360,
        "ai_fps": 24.0,
        "window_seconds": 6.0,
        "stride_seconds": 6.0,
        "extra_ai_delay_ms": 0.0,
        "jpeg_quality": 75,
        "h264_batch_size": 1,
        "max_duration_sec": 20.0,
    },
]


def build_experiment_configs_from_list() -> List[ExperimentConfig]:
    configs: List[ExperimentConfig] = []
    for item in EXPERIMENT_LIST:
        cfg = ExperimentConfig(
            bandwidth_mbps=item["bandwidth_mbps"],
            net_delay_ms=item["net_delay_ms"],
            ai_resolution=item["ai_resolution"],
            ai_fps=item["ai_fps"],
            window_seconds=item["window_seconds"],
            stride_seconds=item.get("stride_seconds", item["window_seconds"]),
            extra_ai_delay_ms=item["extra_ai_delay_ms"],
            jpeg_quality=item["jpeg_quality"],
            h264_batch_size=item["h264_batch_size"],
            max_duration_sec=item.get("max_duration_sec", 10.0),
        )
        configs.append(cfg)
    return configs